blank_issues_enabled: true
contact_links:
  - name: Yummi Support
    url: https://t.me/YummiSupport
    about: Direct chat on non-inquiries subjects.
  - name: Documentation
    url: https://Yummi.tech/
    about: Documentation for getting started with bot.
